# Generated by Django 4.2.5 on 2023-09-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafehiveDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('incident', models.CharField(max_length=100)),
                ('emergency', models.BooleanField(default=False)),
            ],
        ),
    ]
